package DistributedTest.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = 'DistributedGradle_Check_Stage_QuickFeedbackLinuxOnly_Trigger' (id = 'DistributedGradle_Check_Stage_QuickFeedbackLinuxOnly_Trigger')
accordingly, and delete the patch script.
*/
changeBuildType(uuid("DistributedGradle_Check_Stage_QuickFeedbackLinuxOnly_Trigger")) {
    params {
        add {
            param("artifactoryPassword", "bot-enterprise-releases")
        }
        add {
            password("artifactoryUsername", "credentialsJSON:ad44a02d-832d-4104-846c-03d87c8b8f56")
        }
    }
}
